require('./components/head/head')
require('./components/menu/menu')
require('./components/banner/banner')
require('./components/pattern/pattern')
require('./components/discount/discount')
console.log('3232434343')