require('./components/head/head')
require('./components/menu/menu')
require('./components/banner/banner')
require('./components/pattern/pattern')
require('./components/discount/discount')
require('./components/moveHeader/moveHeader')
require('./components/moveContent/moveContent')
console.log('3232434343')